### ISSUE TITLE
inference directly

### ISSUE THREAD

**Issue by zhw-zhang** [XiaoyuShi97/FlowFormerPlusPlus#14]
Hello, I am not a professional in this field. But I want to apply your model to some downstream tasks. I see that there are many different weights in the pretrained model. May I ask which one has the best generalization, and how can I simply infer a given video directly? Just as convenient as RAFT.

**Comment by XiaoyuShi97** [comment]
Recommend to use sintel.pth for general purposes.

**Comment by zhw-zhang** [comment]
Thank you, then I can calculate the optical flow by directly using this function [https://github.com/XiaoyuShi97/FlowFormerPlusPlus/blob/main/visualize_flow.py#L154](url) for the image pair, right?

**Comment by XiaoyuShi97** [comment]
Yes. https://github.com/XiaoyuShi97/FlowFormerPlusPlus/blob/main/visualize_flow.py#L161 This function.

**Comment by zhw-zhang** [comment]
thanks, that's all.
