### ISSUE TITLE
visualization function

### ISSUE THREAD

**Issue by zhw-zhang** [XiaoyuShi97/FlowFormerPlusPlus#15]
Hi, I noticed that this code utilizes a [custom visualization function](https://github.com/XiaoyuShi97/FlowFormerPlusPlus/blob/main/visualize_flow.py#L162) but typically we would use the visualization function provided by [PyTorch](https://pytorch.org/vision/stable/generated/torchvision.utils.flow_to_image.html). During my visualization attempts, I observed some discrepancies between the two functions. I must say that your function outperforms the official PyTorch function in terms of color intensity. It provides richer and more vibrant colors. May I ask why you do this, What is the difference between the two?

**Comment by XiaoyuShi97** [comment]
Hi. We follow RAFT to use this visualization algorithm. I believe since RAFT, most papers choose this one.
