### ISSUE TITLE
lot of preliminary issues

### ISSUE THREAD

**Issue by anilrgukt** [XiaoyuShi97/FlowFormerPlusPlus#2]
can you please provide more details on how to run visualize_flow.py? I tried specifying _CN.model='checkpoints/things.pth' and ran into errors while loading the model.

**Comment by anilrgukt** [comment]
I added the below lines in configs/things.py and still the missing keys in the model error.

_CN.transformer = 'percostformer3'
_CN.model = 'checkpoints/things.pth'

**Comment by XiaoyuShi97** [comment]
Hi, sorry for the confusion. As in https://github.com/XiaoyuShi97/FlowFormerPlusPlus/blob/main/visualize_flow.py#L13 , all visualization and evaluation scripts load configs from submission.py. things.py and sintel.py are for training. Let me know if there are other problems.

**Comment by anilrgukt** [comment]
Can you actually run/test the file as a sanity check? I am still getting a lot of missing keys errors. There are some obvious mistakes, in the above line the cfg is imported from configs.submission however the file is named submissions.

**Comment by XiaoyuShi97** [comment]
Sure. Let me check.

**Comment by XiaoyuShi97** [comment]
Hi, I have updated the codes. In submissions.py, use _CN.model to specify the checkpoint to be tested. Let me know if there are other issues.
