### ISSUE TITLE
Question about pre-trained parameter

### ISSUE THREAD

**Issue by Youngkwan-Cho** [XiaoyuShi97/FlowFormerPlusPlus#8]
Hello there,

I have question about the naming of "things_288960.pth" parameter.
What is the meaning of number 288960 after the things_?
Thank you.

**Comment by XiaoyuShi97** [comment]
Hi. FlowFormer additionally trains a model on things at resolution 288*960 with noise augmentation. This resolution is close to that of kitti dataset and leads to much better performance of generalization on kitti dataset. We follow FlowFormer to do so.
