### ISSUE TITLE
Recreating the KITTI generalization on things288960

### ISSUE THREAD

**Issue by starsong98** [XiaoyuShi97/FlowFormerPlusPlus#9]
Hello,

First I would like to thank you for sharing your amazing model codebase.

In a different thread, you mentioned that the things_288960.pth checkpoint refers to the variant that was trained on FlyingThings at 288x960 input size with noise augmentation. However, I have been unable to recreate the numbers in the paper even with that checkpoint, and instead I am getting 4.27 and 14.73 instead of 3.93 and 14.13.

Also, how exactly was the things_288960.pth checkpoint trained? What do I need to change from the original things.py config file? Do I simply need to change the 2 items like it happened in FlowFormer#? Unlike FlowFormer which supplied the things_sharp.py configuration file, it is currently absent in FlowFormer++, so I am not entirely sure how that training was done.

configs/things.py (for training)
```
_CN.image_size = [288, 960]
_CN.add_noise = True
```

**Comment by XiaoyuShi97** [comment]
Hi, which script do you use for testing? Can you reproduce the result using the release things_288960.ckpt?

**Comment by starsong98** [comment]
I used evaluate_FlowFormer_tile.py with the things_288960 ckpt, and the submission config file unchanged, and got:

Validation KITTI: 4.271363, 14.736527

Is there something else I need to change?

**Comment by XiaoyuShi97** [comment]
https://github.com/XiaoyuShi97/FlowFormerPlusPlus/blob/main/evaluate_FlowFormer_tile.py#L27C1-L27C1
Please change this variable to [288,960] and try again. Really sorry for not making it clear and wasting your time!

**Comment by starsong98** [comment]
I am sorry, it still returned still it returned the exact same results (Validation KITTI: 4.271363, 14.736527).

I changed TRAIN_SIZE at line 27 from [432, 960] to [288, 960],
and used this command to run the test:

```
python evaluate_FlowFormer_tile_original.py --model checkpoints/things_288960.pth --eval kitti_validation
```
(it's evaluate_FlowFormer_tile_original.py because I had minimally rewritten evaluate_FlowFormer_tile.py wth things like tqdm progress bars; original.py is copied from the github repo directly)

Is there something else that needs to be changed?

**Comment by XiaoyuShi97** [comment]
https://github.com/XiaoyuShi97/FlowFormerPlusPlus/blob/main/evaluate_FlowFormer_tile.py#L191

Seems this line overwrite the line 27... Please try again.

**Comment by starsong98** [comment]
I changed both lines 27 AND 191 to `TRAIN_SIZE = [288, 960]`.

This returns:
Validation KITTI: 4.200571, 14.612697

It is getting better, but I still cannot seem to replicate the original numbers.

**Comment by XiaoyuShi97** [comment]
https://github.com/XiaoyuShi97/FlowFormerPlusPlus/blob/main/configs/submissions.py#L63
Could you try with 32 iterations?

**Comment by starsong98** [comment]
I went into the submission.py config file, increased decoder_depth to 32.
This returned:
Validation KITTI: 4.062254, 14.553007

**Comment by XiaoyuShi97** [comment]
It is weird. Let me check it, but I may not reply you today as I am busy on another project recently.

**Comment by starsong98** [comment]
That is okay. Thank you for your help.

**Comment by XiaoyuShi97** [comment]
Hi. The released checkpoint should be right. Please try with the updated evaluate script. As the height of kitti images are always larger than 288, padding can lead to performance drop.

**Comment by starsong98** [comment]
It worked! Thank you! On top of the update evaluate script, I also went into submissions.py and changed decoder depth to 32.

Validation KITTI: 3.924170, 14.131492

**Comment by XiaoyuShi97** [comment]
Happy to hear that. Sorry for the caused confusion and good luck on your project!
